import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import vm from 'node:vm';
import dns from 'node:dns/promises';
import {randomBytes} from 'node:crypto';
import {spawn,spawnSync} from 'node:child_process';
import {SUBTYPE_KEY,pairLinks,enrichDraft,detectDuplicate,validateDraft,uniqueId,productFromDraft,productWithListingImage,normalizeUrl,isAffiliate,isMercadoUrl,cleanTitle,titleFromUrl,extractMercadoItemId,extractMercadoUserProductId,canonicalMercadoItemUrl,mercadoItemMetadata,unwrapMercadoVerificationUrl} from '../assets/catalog-core.mjs';

const root=path.resolve(import.meta.dirname,'..'),dataFile=path.join(root,'data/produtos.js'),host='127.0.0.1';let port=Number(process.env.PNM_CATALOG_PORT||4314);
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.txt':'text/plain; charset=utf-8','.md':'text/markdown; charset=utf-8','.zip':'application/zip'};
let lastPackage='';const sessionToken=randomBytes(24).toString('hex'),imageBacklogSeen=new Set();

function loadProducts(){const box={};vm.createContext(box);vm.runInContext(`${fs.readFileSync(dataFile,'utf8')}\nthis.__products=PRODUTOS`,box);return box.__products}
function stamp(){return new Date().toISOString().replace(/[:.]/g,'-')}
function json(res,status,data){const body=JSON.stringify(data);res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(body),'cache-control':'no-store'});res.end(body)}
async function body(req,limit=6_000_000){let size=0,chunks=[];for await(const chunk of req){size+=chunk.length;if(size>limit)throw new Error('O lote ultrapassa o limite de 6 MB.');chunks.push(chunk)}return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}')}
function privateIp(ip=''){if(ip.startsWith('::ffff:'))return privateIp(ip.slice(7));if(ip==='::1'||ip==='0:0:0:0:0:0:0:1'||ip.startsWith('fe80:')||ip.startsWith('fc')||ip.startsWith('fd'))return true;const p=ip.split('.').map(Number);return p.length===4&&(p[0]===10||p[0]===127||p[0]===0||p[0]===169&&p[1]===254||p[0]===172&&p[1]>=16&&p[1]<=31||p[0]===192&&p[1]===168||p[0]>=224)}
async function assertPublicUrl(raw){const u=new URL(raw);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||!['','80','443'].includes(u.port))throw new Error('URL remota não permitida.');if(/^(localhost|.*\.localhost)$/i.test(u.hostname))throw new Error('Endereço local bloqueado.');const found=await dns.lookup(u.hostname,{all:true});if(!found.length||found.some(x=>privateIp(x.address)))throw new Error('Destino privado bloqueado.');return u}
async function readLimited(response,max){const reader=response.body?.getReader();if(!reader)return Buffer.alloc(0);let total=0,out=[];for(;;){const {done,value}=await reader.read();if(done)break;total+=value.byteLength;if(total>max){reader.cancel();throw new Error('Resposta remota maior que o limite seguro.')}out.push(Buffer.from(value))}return Buffer.concat(out)}
async function remote(raw,{binary=false,max=2_500_000}={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000),recovered=url=>({url,contentType:'text/html; charset=utf-8',bytes:Buffer.alloc(0),text:'',verificationBlocked:true});try{let current=String(raw),mercadoFallback='';for(let hop=0;hop<=6;hop++){const direct=unwrapMercadoVerificationUrl(current);if(direct){if(direct===mercadoFallback)return recovered(direct);mercadoFallback=direct;current=direct}await assertPublicUrl(current);const response=await fetch(current,{redirect:'manual',signal:controller.signal,headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/131 Safari/537.36','accept-language':'pt-BR,pt;q=0.9,en;q=0.7'}});if(response.status>=300&&response.status<400){const location=response.headers.get('location');if(!location)throw new Error('Redirecionamento sem destino.');const next=new URL(location,current).href,unwrapped=unwrapMercadoVerificationUrl(next);if(unwrapped){if(unwrapped===mercadoFallback)return recovered(unwrapped);mercadoFallback=unwrapped;current=unwrapped}else current=next;continue}if(!response.ok){if(mercadoFallback)return recovered(mercadoFallback);throw new Error(`HTTP ${response.status}`)}const bytes=await readLimited(response,max);return{url:current,contentType:response.headers.get('content-type')||'',bytes,text:binary?'':bytes.toString('utf8')}}if(mercadoFallback)return recovered(mercadoFallback);throw new Error('Muitos redirecionamentos.')}finally{clearTimeout(timer)}}
function meta(html,key){const k=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),patterns=[new RegExp(`<meta[^>]+(?:property|name)=["']${k}["'][^>]+content=["']([^"']+)["'][^>]*>`,'i'),new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${k}["'][^>]*>`,'i')];return patterns.map(r=>html.match(r)?.[1]).find(Boolean)||''}
function jsonLdProduct(html){for(const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const raw=JSON.parse(m[1]),queue=Array.isArray(raw)?[...raw]:[raw];while(queue.length){const x=queue.shift();if(!x||typeof x!=='object')continue;if(Array.isArray(x)){queue.push(...x);continue}if(String(x['@type']||'').toLowerCase()==='product')return{name:x.name||'',brand:typeof x.brand==='string'?x.brand:x.brand?.name||'',image:Array.isArray(x.image)?x.image[0]:x.image||''};queue.push(...Object.values(x).filter(v=>v&&typeof v==='object'))}}catch{}}return{}}
function metadataFrom(page){const ld=jsonLdProduct(page.text),rawTitle=cleanTitle(meta(page.text,'og:title')||ld.name||page.text.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||''),title=/^mercado\s*livre$/i.test(rawTitle)?titleFromUrl(page.url):(rawTitle||titleFromUrl(page.url)),image=meta(page.text,'og:image')||ld.image||'',itemId=extractMercadoItemId(page.url,image,page.text),userProductId=extractMercadoUserProductId(page.url,page.text);return{resolvedUrl:normalizeUrl(page.url),title,brand:ld.brand||'',image:normalizeUrl(image),itemId,userProductId,status:page.verificationBlocked?'url-recuperada':title||image?'capturado':'sem-metadados'}}
async function mercadoMetadata(page,base){const itemId=extractMercadoItemId(base.itemId,page.url,base.image,page.text);if(!itemId)return base;const fallback={...base,itemId,resolvedUrl:/\/social\//i.test(base.resolvedUrl||'')?canonicalMercadoItemUrl(itemId):base.resolvedUrl};try{const item=JSON.parse((await remote(`https://api.mercadolibre.com/items/${itemId}`)).text);let category={};if(item.category_id)try{category=JSON.parse((await remote(`https://api.mercadolibre.com/categories/${encodeURIComponent(item.category_id)}`)).text)}catch{}return mercadoItemMetadata(item,category,fallback)}catch{return fallback}}
async function metadataForUrl(target){const page=await remote(target);const basic=metadataFrom(page);return isAffiliate(target)||isMercadoUrl(page.url)?mercadoMetadata(page,basic):basic}
async function analyzeOne(base,context){let metadata={status:'local'};const target=base.linkOriginal||base.linkAfiliado;try{if(target){metadata=await metadataForUrl(target);if(isAffiliate(base.linkAfiliado)&&isMercadoUrl(metadata.resolvedUrl))base.linkOriginal=metadata.resolvedUrl}}catch(e){metadata={status:'indisponivel',error:e.name==='AbortError'?'Tempo de resposta excedido':e.message}}return enrichDraft(base,{...context,metadata})}
async function pool(items,limit,fn){const out=new Array(items.length);let next=0;async function worker(){for(;;){const i=next++;if(i>=items.length)return;out[i]=await fn(items[i],i)}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}
async function imageBacklog(payload={}){const products=loadProducts(),limit=Math.max(1,Math.min(12,Number(payload.limit)||6)),pending=products.filter(p=>!['oficial','anuncio'].includes(p.imagemTipo)&&!imageBacklogSeen.has(p.id)&&(p.linkOriginal||p.linkAfiliado)).slice(0,limit);for(const p of pending)imageBacklogSeen.add(p.id);const drafts=await pool(pending,4,async p=>{let metadata={status:'indisponivel'};try{metadata=await metadataForUrl(p.linkOriginal||p.linkAfiliado)}catch(e){metadata={status:'indisponivel',error:e.name==='AbortError'?'Tempo de resposta excedido':e.message}}const subtype=SUBTYPE_KEY[p.tipoProduto]?p[SUBTYPE_KEY[p.tipoProduto]]||'':'';return{uid:`imagem-${p.id}`,existingId:p.id,updateMode:'image',selected:Boolean(metadata.image),nome:p.nome,marca:p.marca,tipoProduto:p.tipoProduto,subtipo:subtype,categoria:p.categoria,categoriaId:p.categoriaId,selo:p.selo,faixa:p.faixa||'',linkOriginal:metadata.resolvedUrl||p.linkOriginal||'',linkAfiliado:p.linkAfiliado||'',fonteTecnica:p.fonteTecnica||'',imageUrl:metadata.image||'',imageSource:metadata.image?(metadata.resolvedUrl||p.linkOriginal):'',metadataStatus:metadata.status,metadataError:metadata.error||'',classificationConfidence:'high',classificationReviewed:true,duplicateReviewed:true,duplicate:null,errors:metadata.image?[]:['imagem não localizada']}});return{drafts,scanned:pending.length,remaining:products.filter(p=>!['oficial','anuncio'].includes(p.imagemTipo)&&!imageBacklogSeen.has(p.id)&&(p.linkOriginal||p.linkAfiliado)).length}}
const githubRepo=process.env.PNM_GITHUB_REPO||'edsonrcaustirol/preco-na-mira',githubRemote=process.env.PNM_GITHUB_REMOTE||`https://github.com/${githubRepo}.git`,githubSite=process.env.PNM_GITHUB_SITE||'https://preconamira.com.br/';
const githubPendingFile=path.join(root,'.pnm-github-pending.json');
function gitRun(args,{ok=[0],timeout=120000}={}){const result=spawnSync('git',args,{cwd:root,encoding:'utf8',timeout,env:{...process.env,GIT_TERMINAL_PROMPT:'0'}});if(result.error||!ok.includes(result.status))throw new Error((result.stderr||result.stdout||result.error?.message||'Falha no Git').trim());return result}
function githubState(){if(!fs.existsSync(path.join(root,'.git')))return{configured:false,repository:githubRepo,siteUrl:githubSite,message:'Execute CONFIGURAR-GITHUB.bat uma vez.'};try{const remote=gitRun(['remote','get-url','origin']).stdout.trim(),branch=gitRun(['branch','--show-current']).stdout.trim()||'main',configured=remote.replace(/\/$/,'')===githubRemote.replace(/\/$/,'');return{configured,repository:githubRepo,siteUrl:githubSite,remote,branch,message:configured?'Sincronização automática disponível.':'A origem Git não corresponde ao repositório do Preço na Mira.'}}catch(e){return{configured:false,repository:githubRepo,siteUrl:githubSite,message:e.message}}}
function safeGithubPath(value=''){const p=String(value).replace(/\\/g,'/').replace(/^\.\//,'');return p==='data/produtos.js'||/^data\/importacao-v13_[56]-[a-z0-9_.-]+\.json$/i.test(p)||/^assets\/produtos\/[a-z0-9_.-]+$/i.test(p)?p:''}
function rememberGithubPaths(values=[]){let current=[];try{current=JSON.parse(fs.readFileSync(githubPendingFile,'utf8'))}catch{}const paths=[...new Set([...current,...values].map(safeGithubPath).filter(Boolean))];fs.writeFileSync(githubPendingFile,`${JSON.stringify(paths,null,2)}\n`);return paths}
function syncGithub(values=[]){const state=githubState();if(!state.configured)throw new Error(state.message);const paths=rememberGithubPaths(values.length?values:['data/produtos.js']);gitRun(['add','--',...paths]);const staged=gitRun(['diff','--cached','--quiet'],{ok:[0,1]});if(staged.status===0){if(fs.existsSync(githubPendingFile))fs.unlinkSync(githubPendingFile);return{ok:true,pushed:false,repository:githubRepo,siteUrl:githubSite,message:'O GitHub já está atualizado.'}}const message=`Atualiza catálogo ${new Date().toLocaleString('pt-BR')}`;gitRun(['commit','-m',message]);const pushed=gitRun(['push','origin',state.branch],{timeout:180000});if(fs.existsSync(githubPendingFile))fs.unlinkSync(githubPendingFile);return{ok:true,pushed:true,repository:githubRepo,siteUrl:githubSite,message:'Alterações enviadas. O GitHub Pages iniciou a implantação.',output:pushed.stdout.trim()}}
function catalogStatus(){const products=loadProducts(),official=products.filter(p=>p.imagemTipo==='oficial').length,listing=products.filter(p=>p.imagemTipo==='anuncio').length;return{mode:'direct',version:'13.6.0',sessionToken,products:products.length,official,listing,pending:products.length-official-listing,coverage:Math.round((official+listing)/Math.max(1,products.length)*100),github:githubState()}}
function extFor(type,bytes){if(/webp/i.test(type)||bytes.slice(8,12).toString()==='WEBP')return'webp';if(/png/i.test(type)||bytes.slice(1,4).toString()==='PNG')return'png';if(/jpe?g/i.test(type)||bytes[0]===0xff&&bytes[1]===0xd8)return'jpg';return''}
async function saveListingImage(draft,id,{revision=false}={}){if(!draft.imageUrl)return'';const file=await remote(draft.imageUrl,{binary:true,max:10_000_000}),ext=extFor(file.contentType,file.bytes);if(!ext)throw new Error('O endereço retornado não contém uma imagem reconhecida.');const rel=`assets/produtos/${id}-anuncio${revision?`-${Date.now()}`:''}.${ext}`,target=path.join(root,rel);fs.writeFileSync(target,file.bytes);return rel}
function runValidator(){return spawnSync(process.execPath,[path.join(root,'scripts/validate-v13_6.mjs')],{cwd:root,encoding:'utf8',timeout:120000})}
async function publish(payload){
  const drafts=Array.isArray(payload.products)?payload.products.filter(x=>x&&x.selected!==false):[],catalog=loadProducts(),used=new Set(catalog.map(p=>p.id)),staged=[...catalog],errors=[],newReady=[],imageReady=[];
  for(const d of drafts){
    if(d.updateMode==='image'){
      const current=catalog.find(p=>p.id===d.existingId);
      if(!current)errors.push(`${d.nome||d.existingId}: cadastro original não encontrado`);
      else if(!d.imageUrl)errors.push(`${d.nome}: falta imagem encontrada`);
      else imageReady.push(d);
      continue;
    }
    const duplicate=detectDuplicate(d,staged),missing=validateDraft(d);
    if(duplicate?.level==='exact')errors.push(`${d.nome||d.linkAfiliado}: ${duplicate.reason}`);
    else if(duplicate?.level==='possible'&&!d.duplicateReviewed)errors.push(`${d.nome||d.linkAfiliado}: possível duplicata ainda não revisada`);
    else if(missing.length)errors.push(`${d.nome||d.linkAfiliado}: falta ${missing.join(', ')}`);
    else{newReady.push(d);staged.push({id:`lote-${newReady.length}`,nome:d.nome,marca:d.marca,linkAfiliado:d.linkAfiliado,linkOriginal:d.linkOriginal})}
  }
  if(errors.length)throw new Error(errors.join('\n'));
  if(!newReady.length&&!imageReady.length)throw new Error('Nenhum produto aprovado para publicar.');
  const backupDir=path.join(root,'backups','v13_6',stamp());fs.mkdirSync(backupDir,{recursive:true});fs.copyFileSync(dataFile,path.join(backupDir,'produtos.js'));
  const added=[],updated=[],createdImages=[],warnings=[];
  try{
    for(const d of newReady){const id=uniqueId(d.nome,used);let localImage='';try{localImage=await saveListingImage(d,id);if(localImage)createdImages.push(path.join(root,localImage))}catch(e){warnings.push(`${d.nome}: imagem não baixada (${e.message})`)}added.push(productFromDraft(d,{id,localImage}))}
    for(const d of imageReady){let localImage='';try{localImage=await saveListingImage(d,d.existingId,{revision:true});if(localImage)createdImages.push(path.join(root,localImage))}catch(e){warnings.push(`${d.nome}: imagem não atualizada (${e.message})`);continue}const index=catalog.findIndex(p=>p.id===d.existingId);catalog[index]=productWithListingImage(catalog[index],d,{localImage});updated.push(catalog[index])}
    if(!added.length&&!updated.length)throw new Error(`Nenhuma alteração foi aplicada.\n${warnings.join('\n')}`);
    const all=[...catalog,...added],tmp=`${dataFile}.v13_6.tmp`;fs.writeFileSync(tmp,`const PRODUTOS = ${JSON.stringify(all,null,2)};\n`);fs.copyFileSync(tmp,dataFile);fs.unlinkSync(tmp);
    const check=runValidator();if(check.status!==0)throw new Error(`A validação recusou o lote:\n${check.stdout||''}\n${check.stderr||''}`);
    const manifest={versao:'13.6.0',publicadoEm:new Date().toISOString(),adicionados:added.length,imagensAtualizadas:updated.length,totalCatalogo:all.length,backup:path.relative(root,backupDir),avisos:warnings,produtos:[...added.map(p=>({acao:'adicionado',id:p.id,nome:p.nome,tipo:p.tipoProduto,linkAfiliado:p.linkAfiliado,imagem:p.imagem,imagemTipo:p.imagemTipo})),...updated.map(p=>({acao:'imagem-atualizada',id:p.id,nome:p.nome,tipo:p.tipoProduto,linkAfiliado:p.linkAfiliado,imagem:p.imagem,imagemTipo:p.imagemTipo}))]};
    const manifestName=`importacao-v13_6-${stamp()}.json`;fs.writeFileSync(path.join(root,'data',manifestName),`${JSON.stringify(manifest,null,2)}\n`);const githubPaths=['data/produtos.js',`data/${manifestName}`,...createdImages.map(image=>path.relative(root,image))];rememberGithubPaths(githubPaths);let online={ok:false,configured:githubState().configured,message:githubState().message};if(online.configured)try{online=syncGithub(githubPaths)}catch(e){online={ok:false,configured:true,message:e.message};warnings.push(`GitHub: ${e.message}`)}return{added:added.length,updated:updated.length,total:all.length,warnings,backup:path.relative(root,backupDir),manifest:`data/${manifestName}`,validation:(check.stdout||'').trim(),online}
  }catch(e){fs.copyFileSync(path.join(backupDir,'produtos.js'),dataFile);for(const image of createdImages)if(fs.existsSync(image))fs.unlinkSync(image);throw e}
}
function safeStatic(urlPath){const pathname=decodeURIComponent(urlPath.split('?')[0]||'/');const relative=pathname==='/'?'gerenciador.html':pathname.replace(/^\/+/,''),target=path.resolve(root,relative);if(relative.startsWith('backups/')||relative.startsWith('.tmp-')||relative==='.git'||relative.startsWith('.git/')||target!==root&&!target.startsWith(`${root}${path.sep}`))return'';return target}
function packageProject(){const base=path.basename(root),parent=path.dirname(root),work=path.join(parent,`.tmp-v13_6-package-${process.pid}`),stage=path.join(work,'preco_na_mira_v13_6'),out=path.join(parent,'preco_na_mira_v13_6-atualizado.zip');fs.rmSync(work,{recursive:true,force:true});fs.mkdirSync(work,{recursive:true});fs.cpSync(root,stage,{recursive:true,filter:source=>{const rel=path.relative(root,source);return !rel.startsWith('backups')&&rel!=='.git'&&!rel.startsWith(`.git${path.sep}`)&&!rel.startsWith('.pnm-github')&&!rel.startsWith('.tmp-v13_6-package')&&(!rel.endsWith('.zip')||rel==='site-base.zip')}});if(fs.existsSync(out))fs.unlinkSync(out);let result;if(process.platform==='win32'){const q=s=>`'${s.replace(/'/g,"''")}'`;result=spawnSync('powershell.exe',['-NoProfile','-Command',`Compress-Archive -Path ${q(stage)} -DestinationPath ${q(out)} -Force`],{encoding:'utf8',timeout:180000})}else result=spawnSync('zip',['-qr',out,'preco_na_mira_v13_6'],{cwd:work,encoding:'utf8',timeout:180000});fs.rmSync(work,{recursive:true,force:true});if(result.status!==0||!fs.existsSync(out))throw new Error(result.stderr||result.stdout||'Não foi possível gerar o ZIP.');lastPackage=out;return{file:path.basename(out),size:fs.statSync(out).size,url:'/api/download-package'}}

const server=http.createServer(async(req,res)=>{
  try{
    const u=new URL(req.url||'/',`http://${host}:${port}`);
    if(req.method==='GET'&&u.pathname==='/api/status')return json(res,200,catalogStatus());
    if(req.method==='POST'&&u.pathname.startsWith('/api/')&&req.headers['x-pnm-token']!==sessionToken)return json(res,403,{error:'Sessão local inválida. Recarregue a Central.'});
    if(req.method==='POST'&&u.pathname==='/api/analyze'){const input=await body(req),products=loadProducts(),brands=[...new Set(products.map(p=>p.marca).filter(Boolean))],bases=pairLinks(input.raw||'');const drafts=await pool(bases,4,x=>analyzeOne(x,{brands,products,defaults:input.defaults||{}}));return json(res,200,{drafts,found:bases.length})}
    if(req.method==='POST'&&u.pathname==='/api/image-backlog')return json(res,200,await imageBacklog(await body(req)));
    if(req.method==='POST'&&u.pathname==='/api/publish')return json(res,200,await publish(await body(req)));
    if(req.method==='POST'&&u.pathname==='/api/github-sync')return json(res,200,syncGithub());
    if(req.method==='POST'&&u.pathname==='/api/validate'){const check=runValidator();return json(res,check.status===0?200:422,{ok:check.status===0,output:`${check.stdout||''}${check.stderr||''}`.trim()})}
    if(req.method==='POST'&&u.pathname==='/api/package')return json(res,200,packageProject());
    if(req.method==='GET'&&u.pathname==='/api/download-package'){if(!lastPackage||!fs.existsSync(lastPackage))return json(res,404,{error:'Gere o pacote primeiro.'});res.writeHead(200,{'content-type':'application/zip','content-disposition':`attachment; filename="${path.basename(lastPackage)}"`,'content-length':fs.statSync(lastPackage).size});return fs.createReadStream(lastPackage).pipe(res)}
    const target=safeStatic(u.pathname);if(!target||!fs.existsSync(target)||fs.statSync(target).isDirectory())return json(res,404,{error:'Arquivo não encontrado.'});const ext=path.extname(target).toLowerCase();res.writeHead(200,{'content-type':MIME[ext]||'application/octet-stream','cache-control':/\.(?:js|mjs|json|html)$/.test(ext)?'no-store':'public, max-age=3600'});fs.createReadStream(target).pipe(res)
  }catch(e){json(res,500,{error:e.message||'Erro interno.'})}
});
let listenAttempts=0;
server.on('error',error=>{if(error.code==='EADDRINUSE'&&listenAttempts<9){const occupied=port;port+=1;listenAttempts+=1;console.log(`Porta ${occupied} ocupada; tentando ${port}...`);setTimeout(()=>server.listen(port,host),50);return}console.error(`Não foi possível abrir a Central: ${error.message}`);process.exitCode=1});
server.on('listening',()=>{const url=`http://${host}:${port}/gerenciador.html`;console.log(`Central de Catálogo V13.6 aberta em ${url}`);console.log('Mantenha esta janela aberta durante o uso. Pressione Ctrl+C para encerrar.');if(process.argv.includes('--open')){const child=process.platform==='win32'?spawn('cmd',['/c','start','',url],{detached:true,stdio:'ignore'}):process.platform==='darwin'?spawn('open',[url],{detached:true,stdio:'ignore'}):spawn('xdg-open',[url],{detached:true,stdio:'ignore'});child.unref()}});
server.listen(port,host);
