export const CENTRAL_CONTRACT_VERSION = 'pnm.central-foundation/v1';

export const CENTRAL_AREAS = Object.freeze([
  Object.freeze({ id: 'painel', label: 'Painel', state: 'somente-leitura' }),
  Object.freeze({ id: 'produtos', label: 'Produtos', state: 'somente-leitura' }),
  Object.freeze({ id: 'novo-produto', label: 'Novo Produto', state: 'indisponivel-nesta-etapa' }),
  Object.freeze({ id: 'saude-links', label: 'Saúde dos Links', state: 'somente-leitura' }),
  Object.freeze({ id: 'historico', label: 'Histórico', state: 'somente-leitura' }),
]);

export const CENTRAL_CONTRACTS = Object.freeze({
  version: CENTRAL_CONTRACT_VERSION,
  authentication: Object.freeze({
    provider: 'cloudflare-access',
    enforcement: 'external-boundary-plus-worker-jwt-verification',
    localPassword: false,
    workerJwtVerification: true,
    requiredRuntime: Object.freeze([
      'PNM_CENTRAL_ACCESS_AUD',
      'PNM_CENTRAL_ACCESS_ISSUER',
      'PNM_CENTRAL_EXPECTED_HOST',
    ]),
    accessAssertionHeader: 'cf-access-jwt-assertion',
    algorithm: 'RS256',
    jwksPath: '/cdn-cgi/access/certs',
  }),
  catalog: Object.freeze({
    owner: 'data/produtos-index.js',
    ownerRole: 'canonical',
    centralDatabaseOwner: false,
    projection: Object.freeze({
      contract: 'pnm.central-products/v1',
      source: 'data/produtos-index.js',
      generatedModule: 'central/src/generated/products.mjs',
      authoritative: false,
      readOnly: true,
      networkRequired: false,
    }),
    e2: Object.freeze({
      lifecycleTestCommand: 'npm run test:e2-catalog-operations',
      validateCommand: 'npm run validate:e2-catalog',
      validatorModule: 'scripts/validar-catalogo-operacional.mjs',
    }),
  }),
  affiliateIntegrity: Object.freeze({
    contract: 'pnm.affiliate-integrity/v1',
    command: 'npm run audit:affiliate-integrity',
    cli: 'scripts/audit-affiliate-integrity.mjs',
    mode: 'github-actions-executor',
    centralReadModelContract: 'pnm.central-link-health/v1',
    executionContract: 'pnm.affiliate-integrity-execution/v1',
    monitorContract: 'pnm.affiliate-integrity-monitor/v1',
    executor: Object.freeze({
      kind: 'github-actions',
      workflow: '.github/workflows/auditar-links.yml',
      wrapper: 'scripts/run-affiliate-integrity-workflow.mjs',
      monitorEvaluator: 'scripts/evaluate-affiliate-monitor.mjs',
      scopes: Object.freeze(['full', 'product', 'batch', 'input']),
      scheduled: true,
      scheduleCron: '17 5 * * 0,3',
      scheduleSemantics: 'weekly-sunday-wednesday-intervals-of-three-or-four-days',
      concurrency: 'repository-wide-single-flight',
      arbitraryCommand: false,
      artifactRetentionDays: 30,
    }),
    runStatuses: Object.freeze(['SUCCESS', 'PARTIAL', 'FAILED']),
    classifications: Object.freeze([
      'CORRETO',
      'PROVÁVEL',
      'DIVERGENTE',
      'ANÚNCIO_INDISPONÍVEL',
      'DESTINO_GENÉRICO',
      'PROBLEMA_DE_LINK',
      'NÃO_COMPROVÁVEL',
    ]),
    attentionClassifications: Object.freeze([
      'DIVERGENTE',
      'ANÚNCIO_INDISPONÍVEL',
      'DESTINO_GENÉRICO',
      'PROBLEMA_DE_LINK',
    ]),
    nonVerifiableClassification: 'NÃO_COMPROVÁVEL',
    auditDispatchEnabled: false,
  }),
  githubTransaction: Object.freeze({
    mutationEnabled: false,
    targetBranch: 'main',
    requiredStatusCheck: 'validar',
    flow: Object.freeze(['branch', 'commit', 'pull-request', 'ci', 'merge-controlado']),
    automaticMerge: false,
  }),
  d1: Object.freeze({
    binding: 'PNM_HISTORY_DB',
    databaseName: 'preco-na-mira-central-history',
    migrationDir: 'central/migrations',
    historyContract: 'pnm.central-history/v1',
    schemaVersioned: true,
    bindingPrepared: false,
    remoteProvisioned: false,
    authoritativeCatalog: false,
    retention: Object.freeze({ maxAgeDays: 120, keepRecentRuns: 40, preserveLatestHealthyFull: true }),
    allowedPurposes: Object.freeze(['historico', 'auditorias', 'eventos-operacionais', 'rastreabilidade']),
  }),
  mutations: Object.freeze({
    products: false,
    github: false,
    batch: false,
    automaticLinkCorrection: false,
    automaticLinkMonitor: false,
  }),
});

export function centralCapabilities() {
  return {
    contract: CENTRAL_CONTRACT_VERSION,
    areas: CENTRAL_AREAS,
    owner: CENTRAL_CONTRACTS.catalog.owner,
    catalogProjection: CENTRAL_CONTRACTS.catalog.projection,
    authentication: CENTRAL_CONTRACTS.authentication.provider,
    githubMutationEnabled: CENTRAL_CONTRACTS.githubTransaction.mutationEnabled,
    productMutationEnabled: CENTRAL_CONTRACTS.mutations.products,
    automaticMergeEnabled: CENTRAL_CONTRACTS.githubTransaction.automaticMerge,
    d1AuthoritativeCatalog: CENTRAL_CONTRACTS.d1.authoritativeCatalog,
    d1: CENTRAL_CONTRACTS.d1,
    e2: CENTRAL_CONTRACTS.catalog.e2,
    affiliateIntegrity: CENTRAL_CONTRACTS.affiliateIntegrity,
  };
}
